---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(stringr)
library(tidyverse)
library(DT)
library(dygraphs)
library(lubridate)
library(xts)
library(bakeoff)
library(leaflet)
library(tidygeocoder)

bakers <- bakeoff::bakers
challenges <- bakeoff::challenges
episodes <- bakeoff::episodes
ratings <- bakeoff::ratings

```
  
### Map baker hometowns
```{r}
# hometowns <- bakers %>%
#   select(series, baker, baker_last, hometown, series_winner) %>%
#   mutate(hometown = recode(hometown, 'North London'='London',
#                                      'Durham'='Durham, UK',
#                                      'Newport' = 'Newport, UK',
#                                      'Halifax' = 'Halifax, UK',
#                                      'Portsmouth, Hampshire'='Portsmouth, UK',
#                                      'South Wales'='South Wales, UK',
#                                      'Auchterarder, Perthshire'='Auchterarder, UK',
#                                      'Derby / Holywood, County Down' = 'Derby, UK',
#                                      'Leeds / Luton'='Leeds',
#                                      'Woodford, London / Vilkaviškis, Lithuania'='Woodford, London'))%>%
#   mutate(series = as.character(series)) %>%
#   add_row(baker = c("Valentines Mansion", "Harptree Court", "Welford Park"), 
#           hometown = c("Valentines Mansion", "Harptree Court", "Welford Park"), 
#           series= c("2", "3-4", "5-10")) %>%
#   mutate(series_winner = recode(series_winner, '1'='Winner',
#                                                '0'='Lost',
#                                                .missing ='Tent')) %>%
#   geocode(hometown, method = 'osm', lat = latitude , long = longitude)
# 
# 
# write_csv(hometowns, "baker_hometowns.csv")

```


```{r}
hometowns <- read.csv('baker_hometowns.csv')

pal <- colorFactor(c("red", "navy", "green"), domain = c("Winner", "Lost", "Tent"))

leaflet(hometowns) %>% 
  addTiles() %>% 
  setView(lng = -4.5, lat = 53, zoom = 4.5) %>%
  addProviderTiles(providers$CartoDB.Voyager) %>%
  addCircleMarkers(hometowns$longitude, 
                   hometowns$latitude, 
                   color = ~pal(hometowns$series_winner), 
                   radius = 5, 
                   fill = T,
                   fillOpacity = 0.8,
                   stroke = FALSE,
                   clusterOptions = markerClusterOptions(maxClusterRadius=0),
                   popup = paste(hometowns$baker,
                                 hometowns$series, 
                                 sep = ", Series ")) %>%
  leaflet::addLegend("bottomright", 
            pal=pal,
            values=hometowns$series_winner,
            opacity = 0.8)


```


### Data Table

```{r}
challenges <- challenges %>% 
  filter(!is.na(result)) %>% 
  mutate(season_baker = paste(baker, series, sep = "_"))

episodes_appeared <- bakers %>% 
  mutate(season_baker = paste(baker, series, sep = "_")) %>% 
  select(baker, total_episodes_appeared, season_baker)

star_bakers <- episodes %>% 
  filter(!is.na(sb_name)) %>% 
  select(series, star_bakers, sb_name) %>% 
  filter(sb_name != "Holly, Jason") %>% 
  mutate(season_baker = paste(sb_name, series, sep = "_")) %>% 
  group_by(season_baker) %>% 
  count(star_bakers)

table_data <- left_join(challenges, episodes_appeared, by = "season_baker") %>% 
  filter(result %in% c("Runner-up", "WINNER"))

table_data <- left_join(table_data, star_bakers, by = "season_baker") %>% 
  select(series, baker.x, result, n) %>% 
  mutate(n = coalesce(n, 0))

table_data <- table_data[, c(1, 2, 4, 3)]


datatable(table_data, colnames = c("Series", "Baker", "Times Star Baker", "Result"))
```


### dygraph

```{r}
viewers <- ratings %>% 
  mutate(uk_airdate = ymd(uk_airdate)) %>% 
  select(uk_airdate, viewers_7day, viewers_28day) 

xts <- xts(x = viewers[,-1], order.by = viewers$uk_airdate)

p <- dygraph(xts, main = "Great British Bake Off Viewership", ylab = "# viewers (millions)") %>% 
  dyOptions(stepPlot = TRUE) %>% 
  dySeries("viewers_7day", label = "7 Day Viewers")%>%
  dySeries("viewers_28day", label = "28 Day Viewers") %>% 
  dyHighlight(highlightCircleSize = 4, highlightSeriesBackgroundAlpha = 0.5) %>% 
  dyShading(from = "2010-08-17", to = "2010-09-21", color = "bisque") %>% 
  dyShading(from = "2011-08-18", to = "2011-10-04", color = "bisque") %>% 
  dyShading(from = "2012-08-14", to = "2012-10-22", color = "bisque") %>% 
  dyShading(from = "2013-08-20", to = "2013-10-22", color = "bisque") %>% 
  dyShading(from = "2014-08-06", to = "2014-10-08", color = "bisque") %>% 
  dyShading(from = "2015-08-05", to = "2015-10-07", color = "bisque") %>% 
  dyShading(from = "2016-08-24", to = "2016-10-26", color = "bisque") %>% 
  dyShading(from = "2017-08-29", to = "2017-10-31", color = "bisque") %>% 
  dyShading(from = "2018-08-28", to = "2018-10-30", color = "bisque") %>% 
  dyShading(from = "2019-08-27", to = "2019-10-29", color = "bisque") %>% 
  dyEvent("2014-08-06", "BBC One", labelLoc = "bottom") %>% 
  dyEvent("2017-08-29", "Channel 4", labelLoc = "bottom") %>% 
  dyRangeSelector()
p
```



